//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Objects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TMSEntities : DbContext
    {
        public TMSEntities()
            : base("name=TMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTran> AccountTrans { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ReceiptVoucher> ReceiptVouchers { get; set; }
        public virtual DbSet<RVoucherDet> RVoucherDets { get; set; }
        public virtual DbSet<SalesPerson> SalesPersons { get; set; }
        public virtual DbSet<TranType> TranTypes { get; set; }
        public virtual DbSet<ShowReceipt> ShowReceipts { get; set; }
    
        public virtual ObjectResult<FindCustByID_Result> FindCustByID(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindCustByID_Result>("FindCustByID", idParameter);
        }
    
        public virtual ObjectResult<ShowAccountTrans_Result> ShowAccountTrans(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowAccountTrans_Result>("ShowAccountTrans", idParameter);
        }
    
        public virtual ObjectResult<ShowDetailReceipt_Result> ShowDetailReceipt(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowDetailReceipt_Result>("ShowDetailReceipt", idParameter);
        }
    
        public virtual ObjectResult<ShowReceipt_SlsPer_Result> ShowReceipt_SlsPer(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowReceipt_SlsPer_Result>("ShowReceipt_SlsPer", idParameter);
        }
    
        public virtual ObjectResult<ShowReceipt_Time_Result> ShowReceipt_Time(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowReceipt_Time_Result>("ShowReceipt_Time", dateParameter);
        }
    }
}
