//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptVoucher
    {
        public int VoucherID { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string SlsPerID { get; set; }
        public string Payer { get; set; }
        public string PAddress { get; set; }
        public string MVoucherDescr { get; set; }
        public string MAttachDescr { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public int Released { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public string EmployeeID { get; set; }
        public int Used { get; set; }
    }
}
