//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class RVoucherDet
    {
        public int VoucherDetID { get; set; }
        public Nullable<int> VMainID { get; set; }
        public string CustID { get; set; }
        public string VoucherDescr { get; set; }
        public string AttachDescr { get; set; }
        public string DAcc { get; set; }
        public string CAcc { get; set; }
        public Nullable<decimal> AccAmt { get; set; }
    }
}
