//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public string SlsPerID { get; set; }
        public string SlsPerName { get; set; }
        public string Address { get; set; }
        public string CMT { get; set; }
        public string Phone { get; set; }
        public string CustID { get; set; }
        public Nullable<int> Status { get; set; }
        public string SlsPerDescr { get; set; }
    }
}
