//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranType
    {
        public string TranType1 { get; set; }
        public string TranTypeName { get; set; }
        public string TranTypeDescr { get; set; }
    }
}
